import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout/Layout";
import Providers from "./providers";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ГБПОУ Волгоградский технический колледж",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={inter.className + ' w-full min-h-screen bg-gray-50 text-neutral-800'}>
        <Providers>
          <Header />
          <Layout>
            {children}
          </Layout>
        </Providers>
      </body>
    </html>
  );
}
